import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { createPinia } from "pinia";
import Element from "element-plus";
import "element-plus/dist/index.css";
const app = createApp(App);
app.use(router);
app.use(Element);
app.use(createPinia());
app.mount("#app");
